### ISSUE TITLE
Improve `workflow_dispatch` mode of working by enabling `path` as input

### ISSUE THREAD

**Issue by fwkoch** [curvenote/actions#34]
It would be nice to set up a publish action, where a github user could trigger the action and at that time, specify the path they want published (rather than publishing everything) - https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

We need to make sure things work as expected if `path` is specified as a workflow dispatch input (and probably add an example to the docs).

**Comment by fwkoch** [comment]
Ok - just tested this out, and it works great. No changes are required to this repo, we just need to document how to do this for a user writing their own workflow.

Example:
```
name: Resubmit all articles
on:
  workflow_dispatch:
    inputs:
      path:
        description: Path to pass to submit action
        default: journal-submissions/*
        type: string
        required: true
permissions:
  contents: write
jobs:
  submit:
    uses: curvenote/actions/.github/workflows/submit.yml@v1
    with:
      id-pattern-regex: '^journal-submit-[0-9]{1,10}$'
      venue: cn-testing
      kind: article
      path: ${{ inputs.path }}
    secrets:
      CURVENOTE: ${{ secrets.CURVENOTE_TOKEN }}
      GITHUB: ${{ secrets.GITHUB_TOKEN }}
```

Gives this dialog:

![Image](https://github.com/user-attachments/assets/fe040a7c-a687-45f4-bdba-24b1366cb0c3)
